export const PUERTAS_IMAGE_REGISTRY = {
  simples: {
    m1: "m1",
    m1vr: "m1vr",
    m2: "m2",
    m3: "m3",
    m3vr: "m3vr",
    m4: "m4",
    m4vr: "m4vr",
    m5: "m5",
    m6: "m6",
    m7: "m7",
    m8: "m8",
    m9: "m9",
    m10: "m10",
    m10vr: "m10vr",
    m11: "m11",
    m12: "m12",

    mpanel: "mpanel",
    mpanelbarralrecto: "mpanelbarralrecto",
    mpanelbarralcurvo: "mpanelbarralcurvo",
  },

  dobles: {
    m1: "m1doble",
    m1vr: "m1vrdoble",
    m2: "m2doble",
    m3: "m3doble",
    m3vr: "m3vrdoble",
    m4: "m4doble",
    m4vr: "m4vrdoble",
    m5: "m5doble",
    m6: "m6doble",
    m7: "m7doble",
    m8: "m8doble",
    m9: "m9doble",
    m10: "m10doble",
    m10vr: "m10vrdoble",
    m11: "m11doble",
    m12: "m12doble",

    mpanel: "mpanelsinbarraldoble",
    mpanelbarralrecto: "mpanelbarralrectodoble",
    mpanelbarralcurvo: "mpanelbarralcurvodoble",
  },

  portones: {
    m1: "m1porton",
    m1vr: "m1vrporton",
    m2: "m2porton",
    m3: "m3porton",
    m3vr: "m3vrporton",
    m4: "m4porton",
    m4vr: "m4vrporton",
    m5: "m5porton",
    m6: "m6porton",
    m7: "m7porton",
    m8: "m8porton",
    m9: "m9porton",
    m10: "m10porton",
    m10vr: "m10vrporton",
    m11: "m11porton",
    m12: "m12porton",

    mpanel: "mpanelsinbarralporton",
    mpanelbarralrecto: "mpanelbarralrectoporton",
    mpanelbarralcurvo: "mpanelbarralcurvoporton",
  },
} as const;
